import type { GovernorDecision, GovernorInput, ModelTier, ReasoningEffort, CompressionMode } from "./types.ts";

export type Confidence = "HIGH" | "MEDIUM" | "LOW" | "INSUFFICIENT_DATA";
export interface CounterfactualCandidate { provider: string; model: string; tier: ModelTier; available: boolean; capabilities: string[]; contextWindow?: number; inputPrice?: number; outputPrice?: number; supportsReasoning?: boolean; supportsCompression?: CompressionMode[]; healthScore?: number; }
export interface CounterfactualInput extends GovernorInput { currentProvider?: string; currentModel?: string; currentModelTier?: ModelTier | null; actualInputTokens?: number | null; actualOutputTokens?: number | null; currentCost?: number | null; requiredCapabilities?: string[]; candidates: CounterfactualCandidate[]; }
export interface CounterfactualExecutionPlan { planVersion: string; governorName: string; governorVersion: string; policyVersion: string; recommendedModelTier: ModelTier; selectedProvider: string | null; selectedModel: string | null; resolvedModelTier: ModelTier | null; routingStrategy: string; reasoningEffort: ReasoningEffort; thinkingBudget: number | null; compressionMode: CompressionMode; contextBudget: number | null; maxOutputTokens: number | null; escalationPolicy: GovernorDecision["escalationPolicy"]; estimatedCurrentCost: number | null; estimatedCounterfactualCost: number | null; estimatedSavings: number | null; estimatedSavingsPercent: number | null; tokenReductionOpportunity: number | null; confidence: Confidence; executable: boolean; unresolvedFields: string[]; guardrailResults: Record<string, "YES" | "NO" | "UNKNOWN">; reasons: string[]; liveActiveControl: false; }

function supports(candidate: CounterfactualCandidate, required: string[]): boolean { return required.every((v) => candidate.capabilities.includes(v)); }
function cost(candidate: CounterfactualCandidate, input: CounterfactualInput): number | null { if (candidate.inputPrice == null || candidate.outputPrice == null || input.actualInputTokens == null || input.actualOutputTokens == null) return null; return (candidate.inputPrice * input.actualInputTokens + candidate.outputPrice * input.actualOutputTokens) / 1_000_000; }

export function resolveCounterfactualPlan(input: CounterfactualInput, decision: GovernorDecision): CounterfactualExecutionPlan {
  const unresolved: string[] = []; const required = input.requiredCapabilities ?? [];
  const suitable = input.candidates.filter((c) => c.available && supports(c, required));
  const candidate = decision.modelPolicy.recommendedTier === "preserve" ? suitable.find((c) => c.model === input.currentModel) : suitable.filter((c) => c.tier === decision.modelPolicy.recommendedTier).sort((a, b) => (b.healthScore ?? 0) - (a.healthScore ?? 0))[0];
  if (!candidate) unresolved.push("candidate");
  const capability = candidate ? "YES" : suitable.length ? "UNKNOWN" : "NO";
  const currentCost = input.currentCost ?? null; const counterCost = candidate ? cost(candidate, input) : null;
  if (counterCost == null) unresolved.push("pricingOrUsage");
  const output = Math.min(decision.maxOutputTokens ?? input.requestedMaxOutput ?? 0, input.requestedMaxOutput ?? Number.MAX_SAFE_INTEGER); const outputTokens = output > 0 ? output : null;
  const savings = currentCost != null && counterCost != null ? currentCost - counterCost : null;
  const confidence: Confidence = candidate && counterCost != null ? "HIGH" : candidate ? "LOW" : "INSUFFICIENT_DATA";
  return { planVersion: "3a-v0", governorName: "NativeOmniGovernor", governorVersion: "0.1.0", policyVersion: "v0", recommendedModelTier: decision.modelPolicy.recommendedTier, selectedProvider: candidate?.provider ?? null, selectedModel: candidate?.model ?? null, resolvedModelTier: candidate?.tier ?? null, routingStrategy: decision.routingPolicy.strategy, reasoningEffort: decision.reasoningPolicy.effort, thinkingBudget: null, compressionMode: decision.compressionPolicy.mode, contextBudget: decision.contextBudgetPolicy.maxPromptTokens ?? null, maxOutputTokens: outputTokens, escalationPolicy: decision.escalationPolicy, estimatedCurrentCost: currentCost, estimatedCounterfactualCost: counterCost, estimatedSavings: savings, estimatedSavingsPercent: savings != null && currentCost ? (savings / currentCost) * 100 : null, tokenReductionOpportunity: input.requestedMaxOutput != null && outputTokens != null ? Math.max(0, input.requestedMaxOutput - outputTokens) : null, confidence, executable: Boolean(candidate && capability === "YES"), unresolvedFields: unresolved, guardrailResults: { CAPABILITY_COMPATIBLE: capability, PROVIDER_AVAILABLE: candidate ? "YES" : "UNKNOWN", USER_MAX_OUTPUT_RESPECTED: outputTokens == null || input.requestedMaxOutput == null || outputTokens <= input.requestedMaxOutput ? "YES" : "NO" }, reasons: [`tier=${decision.modelPolicy.recommendedTier}`, `candidate=${candidate ? "capability_compatible" : "unresolved"}`, `routing=${decision.routingPolicy.strategy}`, "execution=record_only"], liveActiveControl: false };
}
