/**
 * #7287 — Codex long-running tasks must document session affinity + stream idle timeout.
 *
 * Users migrating multi-hour Codex workloads hit two silent defaults (affinity off,
 * 10-minute stream idle) and conclude OmniRoute cannot sustain a long session.
 * This guard keeps the Codex guide and the config-codex-cli skill custom block aligned
 * with the knobs that actually exist in settings / env / stream.ts.
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

const guidePath = path.join(repoRoot, "docs/guides/CODEX-CLI-CONFIGURATION.md");
const skillPath = path.join(repoRoot, "skills/config-codex-cli/SKILL.md");

function read(relOrAbs: string): string {
  return fs.readFileSync(relOrAbs, "utf8");
}

test("#7287 Codex guide documents session affinity and stream idle timeout", () => {
  const guide = read(guidePath);

  assert.match(guide, /## Long-running tasks/);
  assert.match(guide, /sessionAffinityTtlMs/);
  assert.match(guide, /STREAM_IDLE_TIMEOUT_MS/);
  assert.match(guide, /FETCH_BODY_TIMEOUT_MS/);
  assert.match(guide, /Affinity TTL/);
  assert.match(guide, /86400/);
  assert.match(guide, /Idle timeout: no data from/);
  assert.match(guide, /stream_idle_timeout|StreamIdleTimeoutError/);
  assert.match(
    guide,
    /heartbeat does not reset|heartbeats do \*\*not\*\* reset|heartbeat does \*\*not\*\* reset/i
  );
  assert.match(guide, /Defaults decision/);
  // Defaults must stay documented as unchanged (opt-in), not flipped in prose as "now on".
  assert.match(guide, /sessionAffinityTtlMs.*0|Default:\*\* `sessionAffinityTtlMs = 0`/s);
  assert.match(guide, /STREAM_IDLE_TIMEOUT_MS.*600000|600000.*10 min/s);
});

test("#7287 config-codex-cli skill mirrors long-running guidance in a custom block", () => {
  const skill = read(skillPath);

  assert.match(skill, /<!-- skill:custom-start -->/);
  assert.match(skill, /<!-- skill:custom-end -->/);
  assert.match(skill, /sessionAffinityTtlMs/);
  assert.match(skill, /STREAM_IDLE_TIMEOUT_MS/);
  assert.match(skill, /FETCH_BODY_TIMEOUT_MS/);
  assert.match(skill, /Idle timeout: no data from/);
  assert.match(skill, /#7287/);
  assert.match(skill, /CODEX-CLI-CONFIGURATION\.md/);
  // Custom block must sit after the generated comment so regenerate preserves it.
  const generatedIdx = skill.indexOf("<!-- generated by src/lib/agentSkills/generator.ts");
  const customIdx = skill.indexOf("<!-- skill:custom-start -->");
  assert.ok(generatedIdx >= 0 && customIdx > generatedIdx);
});

test("#7287 stream idle timeout string still exists in open-sse watchdog", () => {
  const streamSrc = read(path.join(repoRoot, "open-sse/utils/stream.ts"));
  assert.match(streamSrc, /Idle timeout: no data from/);
  assert.match(streamSrc, /stream_idle_timeout/);
  assert.match(streamSrc, /StreamIdleTimeoutError/);
});
